version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'saPassword1@#'
      ACCEPT_EULA: 'Y'
